"""CI/CD regression export (v2 build step 10).

Turns a campaign's BREACHES into a self-contained, replayable regression suite a
company runs in CI on every release — so a fixed vulnerability can't silently
come back.

Source of truth = a JSON suite (export_regression_suite). From it we render:
  - a drop-in pytest file (render_pytest_file) that embeds the suite and replays
    each breach via tools.regression_runner, asserting it no longer breaches;
  - a GitHub Actions example (render_workflow) that runs the suite on every push.

When the campaign carries an approved fix, the suite's target_config gets the
hardened system prompt as system_prompt_override → the tests assert the breach
is held under the fix.
"""

import json
from datetime import datetime, timezone

from agents.verifier import _replay_prompt
from core.contracts import Campaign, Verdict

SUITE_VERSION = 1


def _owasp_id(campaign: Campaign, category):
    report = campaign.report
    if report and category in report.per_category:
        return report.per_category[category].owasp_id
    return None


def export_regression_suite(campaign: Campaign) -> dict:
    """Build a JSON regression suite from a campaign's breached attacks.

    Each case is self-contained: category, replay prompt (crescendo → joined
    transcript), attack_mode, expected_verdict=PASS, severity, owasp_id, and the
    original breach reason. The suite carries the target_config needed to replay;
    if a fix was approved, system_prompt_override is set to the hardened prompt."""
    breached = [r for r in campaign.results if r.verdict == Verdict.FAIL]

    target_config = (
        campaign.target_config.model_dump() if campaign.target_config else None
    )
    if target_config is not None and campaign.fix is not None:
        target_config["system_prompt_override"] = campaign.fix.new_system_prompt

    cases = []
    for i, r in enumerate(breached):
        cases.append(
            {
                "id": f"case-{i}-{r.category.value.lower()}",
                "category": r.category.value,
                "attack_mode": r.attack_mode,
                "replay_prompt": _replay_prompt(r),
                "prompt": r.prompt,
                "transcript": r.transcript,
                "breach_turn": r.breach_turn,
                "expected_verdict": "PASS",
                "severity": r.severity.value,
                "owasp_id": _owasp_id(campaign, r.category),
                "original_reason": r.reason,
            }
        )

    return {
        "version": SUITE_VERSION,
        "campaign_id": campaign.campaign_id,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "target_config": target_config,
        "cases": cases,
    }


# Tokens (not str.format) so the embedded f-strings/braces below stay literal.
_PYTEST_TEMPLATE = r'''"""AUTO-GENERATED by RedAgent — regression suite for campaign __CAMPAIGN_ID__.

Each test replays an attack that BREACHED this target during red-teaming and
asserts it no longer breaches against the configured (hardened) target. Wire this
into CI so a fixed vulnerability can't silently come back.

Requires the redagent backend importable (PYTHONPATH=backend) and target
credentials in the environment (Vertex ADC / GEMINI_API_KEY).
"""

import json

import pytest

from tools.regression_runner import check_case

_SUITE = json.loads(r"""
__SUITE_JSON__
""")

_CASES = _SUITE["cases"]


@pytest.mark.skipif(not _CASES, reason="no breaches to regress")
@pytest.mark.parametrize("case", _CASES, ids=[c["id"] for c in _CASES])
def test_attack_must_not_breach(case):
    result = check_case(case, _SUITE["target_config"])
    assert result["passed"], (
        f"REGRESSION [{case['category']}/{case['attack_mode']}]: a previously fixed "
        f"attack breached again — {result['reason']}"
    )
'''


def render_pytest_file(suite: dict) -> str:
    """Render a drop-in pytest file embedding the suite (one self-contained file)."""
    suite_json = json.dumps(suite, indent=2)
    return _PYTEST_TEMPLATE.replace("__CAMPAIGN_ID__", suite["campaign_id"]).replace(
        "__SUITE_JSON__", suite_json
    )


_WORKFLOW = """\
# AUTO-GENERATED by RedAgent — regression gate for fixed vulnerabilities.
# Runs the exported breach suite on every push so a patched vuln can't return.
name: RedAgent Regression

on:
  push:
  pull_request:

jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Install the RedAgent backend (provides the regression runner + judge).
      - name: Install RedAgent
        run: pip install -e ./backend

      # Replay each previously-breaching attack and assert it no longer breaches.
      # Set the target + model credentials your campaign used:
      #   TARGET_URL              — the deployed app under test (the hardened one)
      #   GOOGLE_GENAI_USE_VERTEXAI / GEMINI_API_KEY — judge model access
      - name: Run regression suite
        env:
          GOOGLE_GENAI_USE_VERTEXAI: "1"
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          PYTHONPATH=backend pytest test_redagent_regression.py -v
"""


def render_workflow() -> str:
    """Render the GitHub Actions example that runs the suite on every push."""
    return _WORKFLOW


def write_suite(campaign: Campaign, out_dir) -> dict:
    """Write suite.json + the pytest file + the workflow to out_dir. Returns the
    written paths (demo / CLI convenience)."""
    from pathlib import Path

    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    suite = export_regression_suite(campaign)

    suite_path = out / "redagent_regression_suite.json"
    test_path = out / "test_redagent_regression.py"
    wf_path = out / "redagent-regression.yml"

    suite_path.write_text(json.dumps(suite, indent=2))
    test_path.write_text(render_pytest_file(suite))
    wf_path.write_text(render_workflow())
    return {"suite": str(suite_path), "test": str(test_path), "workflow": str(wf_path)}
